#!/usr/bin/env bash

set -e
set -x

hostname
whoami
groups
pwd
ls

ls exports


# Convention:
#  firmware-<version>.<platform>.bin
# Example:
#  firmware-3.1.1.esp32.bin

export project=$(cat profiles/constants.prof | egrep "^-D PROJECT_ID="  | sed -E 's/^[^=]*=(.*)/\1/g')
export expo_path="$MYVM_VAR_MAIN4INO_FIRMWARE_BASE_PATH/$project"

function export_firmware_for_platform() {
  local platform=$1

  echo "Exporting files for $platform..."

  python merge-main4ino-description.py $(find -name main4ino-description.json | sort | uniq) > description.json

  find . -name 'firmware-*.'$platform'.bin' > files.list
  find . -name 'firmware-*.'$platform'.elf' >> files.list
  find . -name 'firmware-*.'$platform'.bin' | sed 's#\.bin$#.description.json#g' | xargs -I% cp description.json %
  find . -name 'firmware-*.'$platform'.description.json' >> files.list

  for f in `cat files.list`
  do
    echo "Moving $f..."
    mkdir -p $expo_path
    mv -f $f $expo_path
  done

}

for platform in $(cat .platforms.build)
do
  export_firmware_for_platform "$platform"
done

